name: Test and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

  build:
    needs: [ laravel-tests ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.TARGET }}
          EXCLUDE: "/node_modules/, /.idea/, /.git/, /vendor/, /.github/"
      - name: Composer and migrations
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.USER }}@${{ secrets.HOST }}
          privateKey: ${{ secrets.KEY }}
          command: |
            cd ${{ secrets.TARGET }}
            ln -s public public_html
            ln -s public private_html
            php81 composer.phar install --ignore-platform-reqs
            php81 artisan env:decrypt --key=${{ secrets.ENCRYPT_KEY }} --env=production --force --filename=.env
            php81 artisan migrate --force
            php81 artisan cache:clear
            php81 artisan view:cache
            php81 artisan config:cache
            php81 artisan storage:link


